version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/react-condition
    steps:
      - checkout
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build